"""
Django settings for configuraciones project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q-q_6&o$9=16iz^gz8dn)x#kquw40khd(aw_8elrc++mxzjem$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps personalizadas
    'apps.usuarios',
    'apps.estudiantes',
    'apps.asistencia',
    'apps.cursos',
    'apps.notas',
    'apps.publicaciones',
    'apps.vark',
    'apps.publico',    
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'configuraciones.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'configuraciones.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'beu0hpduvweswzq20pvc',  # Nombre de la base de datos
        'USER': 'uffjaj6pssk7gxuz',  # Usuario
        'PASSWORD': 'SNMfzxXMBbtDLKmHT5Y1',  # Contraseña
        'HOST': 'beu0hpduvweswzq20pvc-mysql.services.clever-cloud.com',  # Host
        'PORT': '3306',  # Puerto por defecto de MySQL
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'apps' / 'publico' / 'static',      # Para la aplicación 'publico'
    BASE_DIR / 'apps' / 'estudiantes' / 'static',  # Para la aplicación 'estudiantes'
    BASE_DIR / 'apps' / 'asistencia' / 'static',   # Para la aplicación 'asistencia'
    BASE_DIR / 'apps' / 'cursos' / 'static',       # Para la aplicación 'cursos'
    BASE_DIR / 'apps' / 'notas' / 'static',        # Para la aplicación 'notas'
    BASE_DIR / 'apps' / 'publicaciones' / 'static',# Para la aplicación 'publicaciones'
    BASE_DIR / 'apps' / 'vark' / 'static',         # Para la aplicación 'vark'
    BASE_DIR / 'apps' / 'usuarios' / 'static',     # Para la aplicación 'usuarios'
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
